import AuthProvider from '@/components/Provider'
import '../styles/globals.css'
import { Inter } from 'next/font/google'
import NavBar from '@/components/NavBar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
    title: 'Splitwise',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <AuthProvider>

                    <NavBar />
                    <div style={{ margin: "75px 10px" }}>
                        {children}
                    </div>
                </AuthProvider>
            </body>
        </html>
    )
}